releases:
  - name: traefik
    namespace: kube-system
    chart: stable/traefik
    values:
      - dashboard:
          domain: traefik.{{ .Environment.Values.domain | default "foo.com" }}
          enabled: true
        rbac:
          enabled: true
        kubernetes:
          ingressEndpoint:
            useDefaultPublishedService: true
