releases:
  - name: metrics-server
    namespace: kube-system
    chart: stable/metrics-server
    values:
      - image:
          repository: gcr.io/google_containers/metrics-server-arm
        args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP
