apiVersion: v1
kind: Namespace
metadata:
  name: userapps
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-claim
  namespace: userapps
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  namespace: userapps
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea-container
        image: kunde21/gitea-arm:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 22
          name: ssh
        volumeMounts:
          - name: nfs-pvc
            mountPath: "/data"
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: gitea-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: userapps
spec:
  selector:
    app: gitea
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 80
    name: http
  - protocol: TCP
    targetPort: 22
    port: 22
    name: ssh
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea.pikube.movishell.pl
  namespace: userapps
spec:
  rules:
  - host: gitea.pikube.movishell.pl
    http:
      paths:
      - backend:
          serviceName: gitea-service
          servicePort: 80
