apiVersion: v1
kind: Namespace
metadata:
  name: kubernator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernator
  labels:
    k8s-app: kubernator
  name: kubernator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kubernator
  template:
    metadata:
      labels:
        k8s-app: kubernator
    spec:
      containers:
      - image: dvdmuckle/kubernator-arm
        name: kubernator
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: kubernator
  labels:
    k8s-app: kubernator
  name: kubernator
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: kubernator
  type: ClusterIP
