---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: install }

- hosts: controller
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/controller }

- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - {role: k3s/node }
