---
- hosts:
    - all
  tasks:

  - name: Disable swap and apt-daily
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    loop:
       - apt-daily.timer
       - apt-daily-upgrade.timer
       - dphys-swapfile.service
       - triggerhappy.service

  - name: Remove syslogd
    apt:
      name: rsyslog
      state: absent
      purge: yes

  - name: Install prereqs
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - busybox-syslogd
      - vim
      - mc
      - libseccomp2
      - gnupg
      - tmux

  - name: Set avaible locales
    copy:
      src: files/locale.gen
      dest: /etc/locale.gen
    register: localechanged

  - name: Set default locale
    copy:
      src: files/locale
      dest: /etc/default/locale
    when: localechanged

  - name: Generate locales
    command: /usr/sbin/locale-gen
    when: localechanged

  - name: Check if cmdline backup exists
    stat:
      path: /boot/cmdline.txt.orig
    register: cmdlinebackup

  - name: Create cmdline backup
    copy:
      remote_src: yes
      src: /boot/cmdline.txt
      dest: /boot/cmdline.txt.orig
    when: not cmdlinebackup.stat.exists

  - name: Check if config backup exists
    stat:
      path: /boot/config.txt.bak
    register: configbackup

  - name: Create config backup
    copy:
      remote_src: yes
      src: /boot/config.txt
      dest: /boot/config.txt.bak
    when: not configbackup.stat.exists

  - name: Set new config
    copy:
      src: files/config.txt
      dest: /boot/config.txt

  - name: Install health script
    copy:
      src: files/health
      dest: /usr/bin/health
      mode: 0755

  - name: Install cpuburn
    copy:
      src: files/cpuburn-a53
      dest: /usr/bin/cpuburn
      mode: 0755

  - name: Install rclocal
    copy:
      src: files/rc.local
      dest: /etc/rc.local
      mode: 0755

  - name: Get boot UUID
    command: /sbin/blkid -s PARTUUID -o value /dev/mmcblk0p2
    register: partuuid

  - name: Enable cgroups
    template:
      src: templates/cmdline.txt.j2
      dest: /boot/cmdline.txt
    register: cmdlineupdated
    when: partuuid is defined

  - name: Add docker gpg key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      filename: docker-ce
      repo: deb https://download.docker.com/linux/raspbian stretch edge
      state: present

  - name: Install docker
    apt:
      name: docker-ce=18.06.1~ce~3-0~raspbian
      install_recommends: no
      state: present

  - name: Add k8s gpg key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add k8s repository
    apt_repository:
      filename: k8s
      repo: deb http://apt.kubernetes.io kubernetes-xenial main
      state: present

  - name: Install k8s
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - kubeadm
        - kubectl
        - kubelet

  - name: Reboot
    reboot:
